import React, { useState, useEffect } from "react";
import { useApp } from "../context/AppContext";
import { generateDailyPlan, askAiQuestion } from "../services/aiService";
import {
  Sparkles,
  RefreshCw,
  Send,
  CheckCircle2,
  Clock,
  ArrowRight,
  HelpCircle,
  AlertTriangle,
  Flame,
  Bot,
  User,
  Plus,
  Compass,
} from "lucide-react";

export function AiPlannerPage() {
  const { state, addTask, showToast } = useApp();

  const [planResult, setPlanResult] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [userQuery, setUserQuery] = useState("");
  const [isQuerying, setIsQuerying] = useState(false);
  const [chatLog, setChatLog] = useState([
    {
      role: "assistant",
      text: `Hello ${state.profile?.name || "Yashwanth"}! I am your Technical Career Command AI. I continuously analyze your DSA progress (${state.dsa.problems.filter(p => p.status === 'Solved').length} solved), your GSoC 2025 proposal roadmap, and active engineering goals to optimize your deep-work hours. Click "Generate Today's Plan" or ask me any strategic question below.`,
    },
  ]);

  const quickPrompts = [
    "What should I focus on today?",
    "What am I falling behind on?",
    "What should I revise?",
    "Am I spending enough time on GSoC?",
    "Plan my next 7 days.",
  ];

  // Auto-generate plan on first visit if not yet generated
  useEffect(() => {
    handleGeneratePlan();
  }, []);

  const handleGeneratePlan = async (customPrompt = "") => {
    setIsGenerating(true);
    try {
      const plan = await generateDailyPlan(state, customPrompt);
      setPlanResult(plan);
      showToast("Personalized daily plan synthesized");
    } catch (err) {
      console.error(err);
      showToast("Failed to generate plan", "error");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleAskQuestion = async (questionText) => {
    const q = (questionText || userQuery).trim();
    if (!q) return;

    setUserQuery("");
    setChatLog((prev) => [...prev, { role: "user", text: q }]);
    setIsQuerying(true);

    try {
      const answer = await askAiQuestion(state, q);
      setChatLog((prev) => [...prev, { role: "assistant", text: answer }]);
    } catch (err) {
      console.error(err);
      setChatLog((prev) => [
        ...prev,
        { role: "assistant", text: "Encountered an issue processing query. Please retry." },
      ]);
    } finally {
      setIsQuerying(false);
    }
  };

  const adoptPlanTasks = () => {
    if (!planResult || !planResult.plan) return;
    let addedCount = 0;
    planResult.plan.forEach((item) => {
      const alreadyExists = state.tasks.some(
        (t) => t.title.toLowerCase() === item.title.toLowerCase()
      );
      if (!alreadyExists) {
        addTask({
          title: item.title,
          description: `AI Rationale: ${item.why}`,
          category: item.category,
          priority: item.priority || "High",
          estimatedMins: item.durationMins || 45,
          dueDate: new Date().toISOString().split("T")[0],
          notes: "Generated by Shori AI Planner",
        });
        addedCount++;
      }
    });
    showToast(`Adopted ${addedCount} directives into Today's Tasks!`);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
      {/* 1. Header Banner */}
      <div
        className="glass-panel-elevated"
        style={{
          padding: "24px",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: "16px",
          border: "1px solid rgba(168, 85, 247, 0.3)",
          boxShadow: "var(--shadow-glow-violet)",
        }}
      >
        <div>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "6px" }}>
            <div
              style={{
                width: "36px",
                height: "36px",
                borderRadius: "var(--radius-md)",
                background: "linear-gradient(135deg, #7c3aed 0%, #38bdf8 100%)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: "#ffffff",
              }}
            >
              <Sparkles size={20} />
            </div>
            <h1 style={{ fontSize: "22px", fontWeight: 700 }}>AI Personal Command Planner</h1>
            <span className="badge badge-violet">Live Analytical Engine</span>
          </div>
          <p style={{ fontSize: "13px", color: "var(--text-secondary)" }}>
            Synthesizes your DSA revision status, GSoC milestone deadlines, and project pacing to formulate your highest-leverage schedule.
          </p>
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <button
            onClick={() => handleGeneratePlan()}
            disabled={isGenerating}
            className="btn btn-ai"
          >
            <RefreshCw size={15} className={isGenerating ? "spin" : ""} />
            <span>{isGenerating ? "Analyzing Workspace..." : "Regenerate Plan"}</span>
          </button>
        </div>
      </div>

      {/* 2. Personalized Plan Output Section */}
      {planResult && (
        <div className="glass-panel" style={{ padding: "24px", display: "flex", flexDirection: "column", gap: "18px" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: "12px" }}>
            <div>
              <div style={{ fontSize: "12px", color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.06em" }}>
                Executive Assessment
              </div>
              <p style={{ fontSize: "15px", fontWeight: 600, color: "var(--text-white)", marginTop: "4px" }}>
                {planResult.summary}
              </p>
            </div>

            <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
              <span className="badge badge-cyan" style={{ fontSize: "12px", padding: "4px 10px" }}>
                Target: {planResult.recommendedHours || 5.5}h Deep Work
              </span>
              <button onClick={adoptPlanTasks} className="btn btn-primary btn-sm">
                <Plus size={14} />
                <span>Adopt Plan into Tasks</span>
              </button>
            </div>
          </div>

          {/* Plan items list */}
          <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
            {(planResult.plan || []).map((item, idx) => (
              <div
                key={idx}
                style={{
                  padding: "16px 18px",
                  borderRadius: "var(--radius-md)",
                  backgroundColor: "rgba(255, 255, 255, 0.03)",
                  border: "1px solid var(--border-subtle)",
                  display: "flex",
                  flexDirection: "column",
                  gap: "8px",
                  borderLeft:
                    item.category === "DSA"
                      ? "3px solid var(--cyan)"
                      : item.category === "GSoC"
                      ? "3px solid var(--amber)"
                      : "3px solid var(--violet)",
                }}
              >
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                    <span
                      style={{
                        width: "22px",
                        height: "22px",
                        borderRadius: "50%",
                        backgroundColor: "rgba(255, 255, 255, 0.1)",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        fontSize: "12px",
                        fontWeight: 700,
                        color: "var(--text-white)",
                      }}
                    >
                      {idx + 1}
                    </span>
                    <span style={{ fontSize: "14px", fontWeight: 600, color: "var(--text-white)" }}>
                      {item.title}
                    </span>
                  </div>

                  <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                    <span className="badge badge-neutral" style={{ display: "inline-flex", alignItems: "center", gap: "4px" }}>
                      <Clock size={12} />
                      {item.durationMins} mins
                    </span>
                    <span
                      className={`badge ${item.priority === "High" ? "badge-rose" : "badge-amber"}`}
                    >
                      {item.priority}
                    </span>
                  </div>
                </div>

                {/* THE "WHY" EXPLANATION */}
                <div
                  style={{
                    fontSize: "12px",
                    color: "var(--text-secondary)",
                    backgroundColor: "rgba(0, 0, 0, 0.2)",
                    padding: "8px 12px",
                    borderRadius: "var(--radius-sm)",
                    lineHeight: 1.5,
                  }}
                >
                  <strong style={{ color: "var(--cyan)" }}>WHY recommended: </strong>
                  {item.why}
                </div>
              </div>
            ))}
          </div>

          {/* Focus Quote & Strategic Warning */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px", marginTop: "6px" }} className="ai-split-strip">
            {planResult.focusQuote && (
              <div
                style={{
                  padding: "12px 16px",
                  borderRadius: "var(--radius-md)",
                  backgroundColor: "rgba(168, 85, 247, 0.08)",
                  border: "1px solid rgba(168, 85, 247, 0.2)",
                  fontSize: "12px",
                  color: "var(--text-primary)",
                  fontStyle: "italic",
                }}
              >
                "{planResult.focusQuote}"
              </div>
            )}

            {planResult.warningOrAdvice && (
              <div
                style={{
                  padding: "12px 16px",
                  borderRadius: "var(--radius-md)",
                  backgroundColor: "rgba(245, 158, 11, 0.08)",
                  border: "1px solid rgba(245, 158, 11, 0.2)",
                  fontSize: "12px",
                  color: "var(--text-primary)",
                }}
              >
                <strong style={{ color: "var(--amber)" }}>Advisory: </strong>
                {planResult.warningOrAdvice}
              </div>
            )}
          </div>
        </div>
      )}

      {/* 3. Interactive Strategic Advisor Chat & Quick Prompts */}
      <div className="glass-panel" style={{ padding: "24px", display: "flex", flexDirection: "column", gap: "16px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
          <Compass size={18} color="var(--cyan)" />
          <h2 style={{ fontSize: "16px", fontWeight: 700 }}>Ask Shori AI Anything About Your Career Telemetry</h2>
        </div>

        {/* Quick prompt chips */}
        <div style={{ display: "flex", flexWrap: "wrap", gap: "8px" }}>
          {quickPrompts.map((prompt) => (
            <button
              key={prompt}
              onClick={() => handleAskQuestion(prompt)}
              className="btn btn-secondary btn-sm"
              style={{ fontSize: "12px" }}
            >
              <HelpCircle size={13} color="var(--cyan)" />
              <span>{prompt}</span>
            </button>
          ))}
        </div>

        {/* Chat History View */}
        <div
          style={{
            maxHeight: "360px",
            overflowY: "auto",
            display: "flex",
            flexDirection: "column",
            gap: "14px",
            padding: "14px",
            backgroundColor: "rgba(0, 0, 0, 0.25)",
            borderRadius: "var(--radius-md)",
            border: "1px solid var(--border-subtle)",
          }}
        >
          {chatLog.map((msg, index) => {
            const isAi = msg.role === "assistant";
            return (
              <div
                key={index}
                style={{
                  display: "flex",
                  gap: "10px",
                  alignItems: "flex-start",
                  alignSelf: isAi ? "flex-start" : "flex-end",
                  maxWidth: "92%",
                }}
              >
                {isAi && (
                  <div
                    style={{
                      width: "28px",
                      height: "28px",
                      borderRadius: "50%",
                      backgroundColor: "rgba(168, 85, 247, 0.2)",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      flexShrink: 0,
                    }}
                  >
                    <Bot size={16} color="var(--violet)" />
                  </div>
                )}

                <div
                  style={{
                    backgroundColor: isAi ? "rgba(255, 255, 255, 0.05)" : "var(--cyan-subtle)",
                    border: isAi ? "1px solid var(--border-subtle)" : "1px solid rgba(56, 189, 248, 0.3)",
                    borderRadius: "var(--radius-md)",
                    padding: "12px 16px",
                    fontSize: "13px",
                    lineHeight: 1.6,
                    color: "var(--text-white)",
                    whiteSpace: "pre-line",
                  }}
                >
                  {msg.text}
                </div>

                {!isAi && (
                  <div
                    style={{
                      width: "28px",
                      height: "28px",
                      borderRadius: "50%",
                      backgroundColor: "rgba(56, 189, 248, 0.2)",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      flexShrink: 0,
                    }}
                  >
                    <User size={16} color="var(--cyan)" />
                  </div>
                )}
              </div>
            );
          })}

          {isQuerying && (
            <div style={{ display: "flex", alignItems: "center", gap: "8px", color: "var(--violet)", fontSize: "12px" }}>
              <Sparkles size={16} className="spin" />
              <span>Analyzing full command center state...</span>
            </div>
          )}
        </div>

        {/* Query Input Box */}
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleAskQuestion();
          }}
          style={{ display: "flex", gap: "10px" }}
        >
          <input
            type="text"
            placeholder="Ask strategic question (e.g. How can I balance Arrow SIMD PR with Graph DSA practice?)..."
            value={userQuery}
            onChange={(e) => setUserQuery(e.target.value)}
          />
          <button type="submit" disabled={isQuerying || !userQuery.trim()} className="btn btn-ai">
            <Send size={15} />
            <span>Ask AI</span>
          </button>
        </form>
      </div>
    </div>
  );
}
